/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-07-28 06:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.text.*;

public final class modify_005fsession_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("\r\n");

	Connection conn = null;
	Statement stmt= null;
	ResultSet rs = null;
	PreparedStatement pstmt = null;
	String mode = request.getParameter("mode");
	//변경부분
/* 	String userid = request.getParameter("userid"); */
	String userid = (String)session.getAttribute("member_id");
	String username = request.getParameter("username");
	String password = request.getParameter("password");
	String securitynum1 = request.getParameter("securitynum1");
	String securitynum2 = request.getParameter("securitynum2");
	String email = request.getParameter("email"); 
	String zipcode1 = request.getParameter("zipcode1"); 
	String zipcode2 = request.getParameter("zipcode2"); 
	String address1  = request.getParameter("address1"); 
	String address2 = request.getParameter("address2"); 
	String phone1 = request.getParameter("phone1"); 
	String phone2 = request.getParameter("phone2"); 
	String phone3 = request.getParameter("phone3"); 
	String securitynum = new String(); 
	String query = new String();
	String selected = new String();
	StringTokenizer st_securitynum = null;
	StringTokenizer st_zipcode = null;
	StringTokenizer st_phone = null;
	
	java.util.Date yymmdd = new java.util.Date();
	SimpleDateFormat myformat = new SimpleDateFormat("yy-MM-d h:mm a");
	String regdate = myformat.format(yymmdd);
	
	try{
		Class.forName("com.mysql.jdbc.Driver");
	}catch(ClassNotFoundException e){
		out.println(e);
	}
	
	try{
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/member","hkitJeongwon","gj0123");
		stmt = conn.createStatement();
		if(mode.equals("null") || mode.equals("modify")){
			query = "select * from member where userid='"+userid+"'";
			rs = stmt.executeQuery(query);
			
			if(rs.next()){
				username = rs.getString("username");
				password = rs.getString("password");
				
				st_securitynum = new StringTokenizer(rs.getString("securitynum"),"-");
				email = rs.getString("email");
				st_zipcode = new StringTokenizer(rs.getString("zipcode"), "-");
				address1 = rs.getString("address1");
				address2 = rs.getString("address2");
				st_phone = new StringTokenizer(rs.getString("phone"),"-");
				
			if(st_securitynum.hasMoreTokens()){
				securitynum1 = st_securitynum.nextToken();
			}
			
			if(st_securitynum.hasMoreTokens()){
				securitynum2 = st_securitynum.nextToken();
			}
			
			if(st_zipcode.hasMoreTokens()){
				zipcode1 = st_zipcode.nextToken();
			}
			if(st_zipcode.hasMoreTokens()){
				zipcode2 = st_zipcode.nextToken();
			}
			if(st_phone.hasMoreTokens()){
				phone1 = st_phone.nextToken();
			}
			if(st_phone.hasMoreTokens()){
				phone2 = st_phone.nextToken();
			}
			if(st_phone.hasMoreTokens()){
				phone3 = st_phone.nextToken();
			}
			
		}
			rs.close();
			mode = "update";
		}else if(mode.equals("update")){
			query ="update member set username=?, password=?, email=?, zipcode=?, address1=?, address2=?, phone=? where userid='" + userid + "'";
			pstmt = conn.prepareStatement(query);
			pstmt.setString(1, username);
			pstmt.setString(2, password);
			pstmt.setString(3, email);
			pstmt.setString(4, zipcode1+"-"+zipcode2);
			pstmt.setString(5, address1);
			pstmt.setString(6, address2);
			pstmt.setString(7, phone1+"-"+phone2+"-"+phone3);
			pstmt.executeUpdate();
			response.sendRedirect("left_Frame.jsp");
			}
		}catch(SQLException e){
			
	}finally{
		conn.close();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원정보 수정</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction MM_openBrWindow(theURL,winName,features){\r\n");
      out.write("\t\t\twindow.open(theURL,winName,features);\r\n");
      out.write("\t\t}\r\n");
      out.write("\tfunction doSubmit(){\r\n");
      out.write("\t\tform = document.join;\r\n");
      out.write("\t\tif(!form.username.value){\r\n");
      out.write("\t\t\talert('이름을 입력하지 않았습니다.');\r\n");
      out.write("\t\t\tform.username.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(!form.email.value){\r\n");
      out.write("\t\t\talert('Email을 입력하지 않았습니다.');\r\n");
      out.write("\t\t\tform.email.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(!form.email.value.indexOf(\"@\") < 0){\r\n");
      out.write("\t\t\talert('Email주소 형식이 틀립니다.');\r\n");
      out.write("\t\t\tform.email.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(!form.email.value.indexOf(\".\") < 0){\r\n");
      out.write("\t\t\talert('Email주소 형식이 틀립니다.');\r\n");
      out.write("\t\t\tform.email.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(!form.zipcode1.value || !form.zipcode2.value){\r\n");
      out.write("\t\t\talert('우편번호를 입력하지 않았습니다.');\r\n");
      out.write("\t\t\tMM_openBrWindow('zipcode_search.jsp','zipcode_search','scrollbars=yes,width=500,height=250');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!form.address1.value){\r\n");
      out.write("\t\t\talert('주소1를 입력하지 않았습니다.');\r\n");
      out.write("\t\t\tMM_openBrWindow('zipcode_search.jsp','zipcode_search','scrollbars=yes,width-500,height=250');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(!form.address2.value){\r\n");
      out.write("\t\t\talert('주소2를 입력하지 않았습니다.');\r\n");
      out.write("\t\t\tform.address2.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" text=\"#000000\">\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<form name=\"join\" method=\"post\" action=\"modify_session.jsp\">\r\n");
      out.write("\t\t<table width=\"622\" height=\"536\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" bordercolor=\"#A3C2F6\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" class=\"style2\"><font color=\"#FF0000\" size=1>★</font></font><font class=\"style2\">아이디&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"75%\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"userid\" size=\"10\" maxlength=\"10\" class=\"box\" value=\"");
      out.print(userid );
      out.write("\" readonly></font></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">비밀번호&nbsp;&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"75%\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"password\" size=\"12\" maxlength=\"12\" class=\"box\" value=\"");
      out.print(password );
      out.write("\"><font class=\"style2\">다시한번&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password2\" size=\"12\" maxlength=\"12\" class=\"box\" value=\"");
      out.print(password );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<font class=\"style2\">(영문+숫자 4~12자리)</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">이름&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"75%\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"username\" size=\"10\" maxlength=\"10\" class=\"box\" value=\"");
      out.print(username);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">주민등록번호&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\">&nbsp;<input type=\"text\" name=\"securitynum1\" size=\"6\" maxlength=\"6\" class=\"box\" value=\"");
      out.print(securitynum1 );
      out.write("\" readonly>-\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"securitynum2\" size=\"7\" maxlength=\"7\" class=\"box\" value=\"");
      out.print(securitynum2 );
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">EMAIL&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\"><input type=\"text\" name=\"email\" size=\"20\" maxlength=\"50\" class=\"box\" value=\"");
      out.print(email );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">우편번호&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\"><input type=\"text\" name=\"zipcode1\" size=\"3\" maxlength=\"3\" class=\"box\" readonly value=\"");
      out.print(zipcode1);
      out.write("\"> -\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"zipcode2\" size=\"3\" maxlength=\"3\" class=\"box\" readonly value=\"");
      out.print(zipcode2);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" name=\"button\" value=\"우편번호검색\" onClick=\"MM_openBrWindow('zipcode_search.jsp','zipcodesearch','scrollbars=yes,width=500,height=250')\">\r\n");
      out.write("\t\t\t\t\t\t<font color=\"#0099FF\" > 우편번호 검색 버튼을 누르세요.</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">주소&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\">&nbsp;<input type=\"text\" name=\"address1\" size=\"50\" maxlength=\"100\" class=\"box\" readonly value=\"");
      out.print(address1);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font color=\"#FF0000\" size=1>★</font><font class=\"style2\">나머지주소&nbsp;&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\">&nbsp;<input type=\"text\" name=\"address2\" size=\"50\" maxlength=\"100\" class=\"box\" value=\"");
      out.print(address2 );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" align=\"right\"><font class=\"style2\">휴대폰&nbsp;&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"75%\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"phone1\" size=\"4\" maxlength=\"4\" class=\"box\" value=\"");
      out.print(phone1);
      out.write("\"> -\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"phone2\" size=\"4\" maxlength=\"4\" class=\"box\" value=\"");
      out.print(phone2);
      out.write("\"> -\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"phone3\" size=\"4\" maxlength=\"4\" class=\"box\" value=\"");
      out.print(phone3);
      out.write("\"> </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<table width=\"614\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100% align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"mode\" value=\"update\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"등 록\" onClick=\"doSubmit()\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"취 소\" onClick=\"javascript:history.go(-1);\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</td></tr></table>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"639\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"180\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"180\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FECE00\" width=\"44\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FFFFFF\" width=\"1\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FE8C14\" width=\"44\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FFFFFF\" width=\"1\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#8CCA2D\" width=\"44\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FFFFFF\" width=\"1\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#4DAACE\" width=\"44\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#FFFFFF\" width=\"1\" nowrap>&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td bgcolor=\"#A8A8A8\" width=\"453\">&nbsp;</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" height=\"1\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table width=\"638\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FFFFFF\" width=\"638\" nowrap><p align=\"center\"><br>\r\n");
      out.write("\t\t\tCopyright by JeongWon JSP STUDY</p></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
