/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-07-28 07:09:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Object mem_id = session.getAttribute("member_id");
	session.putValue(session.getId(), mem_id);
	String userid = (String)session.getValue(session.getId());
	if(userid == null)
		session.putValue(session.getId(), mem_id);
	String sql = "select * from member where userid=?";
	Connection con = null;
	PreparedStatement pst = null;
	ResultSet rs= null;
	
	try{
		Class.forName("com.mysql.jdbc.Driver");
	}catch(ClassNotFoundException e){
		out.println(e.getMessage());
	}
	
	try{
		con = DriverManager.getConnection("jdbc:mysql://localhost:3306/member","hkitJeongwon","gj0123");
	}catch(SQLException e){
		out.println(e);
	}
	
	try{
		pst = con.prepareStatement(sql);
		pst.setString(1, userid);
		rs = pst.executeQuery();
		if(!(rs.next())){
			out.println("해당되는 회원이 없습니다.");
		}else{
			String username = rs.getString("username");
			String phone = rs.getString("phone");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>");
      out.print(username );
      out.write("회원님 개인 정보관리</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction delconfirm(){\r\n");
      out.write("\t\tif (confirm(\"삭제하시겠습니까?\")){   \r\n");
      out.write("\t\t\tlocation.href=\"delete.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"join\" method=\"post\" action=\"modify_sessoin.jsp\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"userid\" value=\"");
      out.print(userid );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"mode\" value=\"modify\">\r\n");
      out.write("\t\t<table width=\"500\" border=\"1\" bordercolorlight=\"#999999\" bordercolordark=\"#FFFFFF\" cellpadding=\"3\" cellspacing=\"0\" align=\"center\" class=style2>\r\n");
      out.write("\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t<td colspan=\"2\" background=\"image/sky_bar.gif\"> ");
      out.print(username );
      out.write("회원님의 개인정보는 다음과 같습니다.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">아이디</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print( userid );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">이름</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print( username );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">비밀번호</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">보안상 기재하지 않습니다.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">주민등록번호</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print(rs.getString("securitynum") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">EMAIL</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print(rs.getString("email") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">우편번호</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print(rs.getString("zipcode") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">주소1</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print(rs.getString("address1") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">주소2</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">");
      out.print(rs.getString("address2") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"30%\" align=\"right\">휴대폰</td>\r\n");
      out.write("\t\t\t<td width=\"70%\">\r\n");
      out.write("\t\t\t");

				if(phone.equals("--")){
					out.println("<font color='blue'>선택하지 않았습니다.</font>");
				}else{
					out.println(phone);
				}
			
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"확 인\" onClick=\"location='left_Frame.jsp'\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수 정\" onClick=\"location='modify_session.jsp?mode=modify'\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"회원 탈퇴\" onClick=\"delconfirm()\">\r\n");
      out.write("\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

	}
	rs.close();
	con.close();
	pst.close();
	}catch(SQLException e){
		out.println(e);
		}
		
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
