/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-07-20 07:07:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class filegb_005fsave2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("\r\n");

	String board_file = "C:/Pro/write.txt";
	String email=null;
	File check=new File(board_file);
	
	if(!check.exists()){
		FileWriter filew = new FileWriter(board_file);
		filew.write("");
		filew.close();
	}
	
	if(request.getParameter("email") !=""){
		email = "<A href=mailto:" ;
		email += request.getParameter("email");
		email += ">" + request.getParameter("email");
		email += "</A>";
	}
	
	try{
		PrintWriter pw = new PrintWriter(new FileWriter(board_file, true));
		pw.println("<table border='0' width='600' cellspacing='0' cellpadding='2'>");
		pw.println("<tr align='right'>");
		pw.println("<td height='22'>&nbsp;</td></tr>");
		pw.println("<tr align='center'>");
		pw.println("<td height='1' bgcolor='#1F4F8F'></td>");
		pw.println("</tr>");
		pw.println("<tr align='center' bgcolor='#DFEDFF'>");
		pw.println("<td class='button' bgcolor='#DFEDFF'>");
		pw.println("<div align='left'><font size='2'>"+request.getParameter("subject"));
		pw.println("</div></td>");
		pw.println("</tr>");
		pw.println("<tr align='center' bgcolor='#FFFFFF'>");
		pw.println("<td align='center' bgcolor='#F4F4F4'>");
		pw.println("<table width='100%' border='0' cellpadding='0' cellspacing='4'>");
		pw.println("<tr bgcolor='#F4F4F4'>");
		pw.println("<td width='13%' height='7'></td>");
		pw.println("<td width='38%' height='7'>글쓴이:" + request.getParameter("name") + "</td>");
		pw.println("<td width='38%' height='7'>E-mail: " + email +"</td>");
		pw.println("<td width='11%' height='7'></td>");
		pw.println("</tr>");
		pw.println("<tr bgcolor='#F4F4F4'>");
		pw.println("<td width='13%'></td>");
		pw.println("<td colspan=2>작성일:" + (new java.util.Date()).toLocaleString() + "</td>");
		pw.println("<td width='11%'></td>");
		pw.println("</tr></table>");
		pw.println("</td></tr>");
		pw.println("<tr align='center'>");
		pw.println("<td bgcolor='#1F4F8F' height='1'></td>");
		pw.println("</tr>");
		pw.println("<tr align='center'>");
		pw.println("<td style='padding:10 0 0 0'>");
		pw.println("<div align='left'><br>");
		pw.println("<font size='3' color='#333333'><PRE>"+request.getParameter("content"));
		pw.println("</PRE></div");
		pw.println("<br>");
		pw.println("</td></tr>");
		pw.println("<tr align='center'>");
		pw.println("<td class='button' height='1'></td>");
		pw.println("</tr>");
		pw.println("<tr align='center'>");
		pw.println("<td height='1' bgcolor='#1F4F8F'></td>");
		pw.println("</tr>");
		pw.println("</table>");
		pw.close();
		
	}catch(IOException e){
		out.println(e.getMessage());
	}

      out.write("\r\n");
      out.write("\r\n");
      if (true) {
        _jspx_page_context.forward("filegb_show.jsp");
        return;
      }
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
